"""Removed Non-use

Revision ID: cd094e37313e
Revises: 32656ad0b5aa
Create Date: 2024-01-21 20:48:03.537846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd094e37313e'
down_revision = '32656ad0b5aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usercredit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usercredit',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('positives', sa.INTEGER(), nullable=True),
    sa.Column('negatives', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
